export const commonHabits = [
    "Drink more water",
    "Eat a healthy breakfast",
    "Exercise for 30 minutes",
    "Read a book for 15 minutes",
    "Meditate for 10 minutes",
    "Write in a journal",
    "Practice gratitude",
    "Get 8 hours of sleep",
    "Wake up early",
    "Go for a walk",
    "Stretch your body",
    "Learn a new word",
    "Practice a new language",
    "Play a musical instrument",
    "Draw or paint",
    "Write a short story or poem",
    "Listen to a podcast",
    "Watch a documentary",
    "Learn a new skill",
    "Take an online course",
    "Work on a side project",
    "Network with people in your field",
    "Update your resume",
    "Apply for a new job",
    "Save money",
    "Create a budget",
    "Track your expenses",
    "Invest in stocks or mutual funds",
    "Pay off debt",
    "Cook a healthy meal",
    "Eat more fruits and vegetables",
    "Avoid processed foods",
    "Limit your sugar intake",
    "Quit smoking",
    "Reduce your alcohol consumption",
    "Spend time with loved ones",
    "Call a friend or family member",
    "Volunteer for a cause you care about",
    "Donate to charity",
    "Help a neighbor",
    "Be kind to strangers",
    "Practice active listening",
    "Be more patient",
    "Forgive someone",
    "Let go of grudges",
    "Practice self-compassion",
    "Take a break from social media",
    "Spend time in nature",
    "Declutter your home",
    "Organize your workspace",
    "Clean your home",
    "Do your laundry",
    "Meal prep for the week",
    "Plan your day",
    "Set goals for the week",
    "Review your goals",
    "Celebrate your accomplishments",
    "Learn from your mistakes",
    "Ask for help when you need it",
    "Say no to things that don't align with your goals",
    "Take a different route to work",
    "Try a new restaurant",
    "Visit a museum or art gallery",
    "Go to a concert or play",
    "Travel to a new city or country",
    "Learn to dance",
    "Take a cooking class",
    "Join a book club",
    "Start a blog or vlog",
    "Take up a new hobby",
    "Do something that scares you",
    "Step out of your comfort zone",
    "Be more spontaneous",
    "Laugh more",
    "Smile at strangers",
    .
    .
    .
];
